name: build push image
on:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"
    branches:
      - "main"
      - "feature/**"

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      shashort: ${{ steps.ssha.outputs.sha_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short sha
        id: ssha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker tag
        id: docker_meta
        run: |
          if [[ ${{ github.ref_name }} == feature* ]]; then
            echo "DOCKER_TAG=${{ github.sha }}-feature" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Login to QUAY
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push to QUAY
        uses: docker/build-push-action@v4
        id: quay-build-push
        with:
          push: true
          tags: quay.io/${{secrets.QUAY_REPO}}/py-webhook-alert:${{ env.DOCKER_TAG }}
